spring:
  application:
    name: Worker-Service

  web:
    resources:
      static-locations: file:uploads/

  datasource:
    url: jdbc:mysql://localhost:3306/worker_service
    username: root
    password: root9721


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


  #remove below code if you want to manual circuit breaker
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

server:
  port: 8083

# ==========================
# Eureka Configuration
# ==========================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# ==========================
# Actuator Configuration
# ==========================
management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents

  endpoint:
    health:
      show-details: always

  health:
   circuitbreakers:
      enabled: true

# ==========================
# Resilience4j Circuit Breaker
# ==========================
resilience4j:
  circuitbreaker:
    configs:
      default:
        record-failure-predicate:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      record-exceptions:
          - feign.FeignException
          - feign.RetryableException

    instances:
      Rating-Service:
        baseConfig: default
      User-Service:
        baseConfig: default

